// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQB6xLBcuy0j4QE-I6MfdPjhABt0BtcXs',
    appId: '1:1066311481389:web:ba5c35ac5331484fdde0a4',
    messagingSenderId: '1066311481389',
    projectId: 'cipherschools-assignment-007',
    authDomain: 'cipherschools-assignment-007.firebaseapp.com',
    storageBucket: 'cipherschools-assignment-007.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEc21pmj_NXK8J6UAgfpty2wj-GNJ9D4Q',
    appId: '1:1066311481389:android:6bc1837cf8980860dde0a4',
    messagingSenderId: '1066311481389',
    projectId: 'cipherschools-assignment-007',
    storageBucket: 'cipherschools-assignment-007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgLEeGAhL9FOGIIso5G1qTmgQ6gC_781U',
    appId: '1:1066311481389:ios:18db360ab0e83e7adde0a4',
    messagingSenderId: '1066311481389',
    projectId: 'cipherschools-assignment-007',
    storageBucket: 'cipherschools-assignment-007.appspot.com',
    iosBundleId: 'com.example.cipherschoolsFlutterAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgLEeGAhL9FOGIIso5G1qTmgQ6gC_781U',
    appId: '1:1066311481389:ios:d7effebe0e3b126edde0a4',
    messagingSenderId: '1066311481389',
    projectId: 'cipherschools-assignment-007',
    storageBucket: 'cipherschools-assignment-007.appspot.com',
    iosBundleId: 'com.example.cipherschoolsFlutterAssignment.RunnerTests',
  );
}
